export const vars = {
    isMouseDown: false,
    sudokuGrid: document.querySelector('.sudoku-grid'),
    cells: document.querySelector('.sudoku-grid').querySelectorAll('.cell'),
    resetButton: document.querySelector('.reset-button'),
    undoButton: document.querySelector('.undo-button'),
    redoButton: document.querySelector('.redo-button'),
    keypadButtons: document.querySelectorAll('.keypad-button'),
    digitsCentreButton: document.querySelector('.centre-button'),
    digitsNormalButton: document.querySelector('.normal-button'),
    digitsCornerButton: document.querySelector('.corner-button'),
    digitsColourButton: document.querySelector('.colour-button'),
    homeButton: document.querySelector('.home-button'),
    myPuzzlesButton: document.querySelector('.my-puzzles-button'),
    findPuzzlesButton: document.querySelector('.find-puzzles-button'),
    setterModeButton: document.querySelector('.setter-mode-button'),
    ctrlOrShiftPressed: false,
    cell: null,
    undoHistory: [],
    redoHistory: [],
    actionID: 0,
    isCentreText: false,
    isCornerText: false,
    isColourText: false,
    buttonClicked: false,
};
